### PR TITLE
the Chinese version.

### PR DESCRIPTION
**Pull request by nagexiucai**
I noticed that there is a new_branch, but i just complete the translation of current master.
Though most illustrations are copies from master, they will be edited with Chinese notes later or pure Chinese version screenshots(even GIFs) when complete luna-studio's i18n-zh-cn.

### CODE REVIEW

**Comment by kustosz** [comment]
Yeah, the `new_branch` is to be removed, looks like an experiment done directly from GitBook.
Now, I have tested this with GitBook and this won't work just yet. There's some shuffling existing files around to be done, but I can handle this myself (just tried the structure and there's a ton of trouble with gitbook).
However, there's an issue of `SUMMARY.md` file – this is necessary (serves as a table of contents). Please add this – poinitng to the right files, I won't be able to publish unless every entry inside the SUMMARY.md points to an existing folder, that's how gitbook works.
Also, we'll need to ask you to sign our CLA before merge here: https://cla-assistant.io/luna/luna-book?pullRequest=19

**Comment by nagexiucai** [comment]
@kustosz Thanks!
And bob-nx is me too, aka bob-nagexiucai(like nickname in discord), I have signed the CLA.

There are a few differences in contents(SUMMARY.md):

I would like to make "basic data types" and "creating custom data types" under "data types" for comparision(then better for understanding).

I put "what you need to dive in" and "learning the interface" together in one file(starting-out.md) because they are so short currently.

**Comment by nagexiucai** [comment]
@CLAassistant And in order to understand CLA of [luna-book](https://cla-assistant.io/luna/luna-book), i had translated it into [Chinese](https://github.com/LunaCN/luna-book-zh-cn/blob/master/CLA.md "CLA of luna-book-zh-cn").
I know how important the clear property rights are, i am willing to waive any rights of luna-book's Translation except for the right of signature.

**Comment by kustosz** [comment]
Ok, seems like we're almost there. I have just deployed and there's still some problems with the summary – the sections that don't have any document linked to them also don't expand in the menu. You can preview the current version here: https://luna-lang.gitbooks.io/docs/content/v/zh-cn/zh-cn/ – notice how the menu on the left hand side does not work for some options.

**Comment by nagexiucai** [comment]
@kustosz I have added 'jump' pages for each section without link then try to complete menu in gitbook.

**Comment by nagexiucai** [comment]
I checked zh-cn's link on GitBook just now, it seems ok now. Close the PR :)

**Pull request closed without merging**
